/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smc_vidproc_call_cpu */

#ifndef _Included_com_smc_vidproc_call_cpu
#define _Included_com_smc_vidproc_call_cpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smc_vidproc_call_cpu
 * Method:    detect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smc_vidproc_call_1cpu_detect
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
